version: '3.2'
services:
    zookeeper:
        build:
            context: ./sc4-zookeeper
        image: bde2020/pilot-sc4-zookeeper
        hostname: zookeeper
        container_name: zookeeper
        environment:
            - MYID=1
            - DELAY=5
            - INIT_DAEMON_STEP=setup_zookeeper
            - ENABLE_INIT_DAEMON = "true"
        expose:
            - "2181"
        ports:
            - "2181:2181"
    kafka:
        build:
            context: ./sc4-kafka
        image: bde2020/pilot-sc4-kafka
        hostname: kafka
        container_name: kafka
        environment:
            - ZOOKEEPER_SERVERS=zookeeper:2181
            - INIT_DAEMON_STEP=setup_kafka
            - ENABLE_INIT_DAEMON = "true"
            - INITIAL_TOPICS="taxi"
        depends_on:
            - zookeeper
        expose:
            - "9092"

    namenode:
      image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
      hostname: namenode
      container_name: namenode
      environment:
              CSS_SOURCE: "hadoop"
              CLUSTER_NAME: test
              INIT_DAEMON_STEP: "setup_hdfs"
              VIRTUAL_HOST: hdfs-namenode.big-data-europe.local
      env_file:
            - ./config/hadoop/hadoop.env
      volumes:
            - ./data/hadoop/namenode:/hadoop/dfs/name
      expose:
            - "50070"
    datanode:
        image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
        hostname: datanode
        container_name: datanode
        environment:
              CSS_SOURCE: "hadoop"
              VIRTUAL_HOST: hdfs-datanode.big-data-europe.local
              VIRTUAL_PORT: "50075"
        env_file:
            - ./config/hadoop/hadoop.env
        volumes:
            - ./data/hadoop/datanode:/hadoop/dfs/data
        depends_on:
            - namenode
        expose:
            - "50075"
    resourcemanager:
        image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
        hostname: resourcemanager
        container_name: resourcemanager
        expose:
            - "8031"
            - "8088"
        environment:
            VIRTUAL_HOST: hdfs-resourcemanager.demo.big-data-europe.local
            VIRTUAL_PORT: "8088"
            CSS_SOURCE: "hadoop-resource-manager"
        env_file:
            - ./config/hadoop/hadoop.env
        depends_on:
              - namenode
              - datanode
    historyserver:
        image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
        hostname: historyserver
        container_name: historyserver
        volumes:
            - ./data/hadoop/historyserver:/hadoop/yarn/timeline
        env_file:
            - ./config/hadoop/hadoop.env
        environment:
            VIRTUAL_HOST: hdfs-historyserver.demo.big-data-europe.local
            VIRTUAL_PORT: "8188"
            CSS_SOURCE: "hadoop-history-server"
        depends_on:
              - namenode
              - datanode
    nodemanager:
        image: bde2020/hadoop-nodemanager:1.1.0-hadoop2.7.1-java8
        hostname: nodemanager
        container_name: nodemanager
        expose:
            - "8042"
        environment:
            VIRTUAL_HOST: hdfs-nodemanager.demo.big-data-europe.local
            VIRTUAL_PORT: "8042"
            CSS_SOURCE: "hadoop-node-manager"
        env_file:
            - ./config/hadoop/hadoop.env
        depends_on:
              - namenode
              - datanode
    filebrowser:
        image: bde2020/hdfs-filebrowser
        hostname: filebrowser
        container_name: filebrowser
        expose:
            - "8088"
        environment:
              NAMENODE_HOST: namenode
              VIRTUAL_HOST: hue.big-data-europe.local
              VIRTUAL_PORT: "8088"
        depends_on:
            - namenode
            - datanode
    flink-master:
        image: bde2020/flink-master:1.2.0-hadoop2.7
        hostname: flink-master
        container_name: flink-master
        expose:
              - "8081"
              - "8080"
        environment:
              CSS_SOURCE: "flink-dashboard"
              INIT_DAEMON_STEP: "setup_flink"
              VIRTUAL_HOST: flink-master.big-data-europe.local
              VIRTUAL_PORT: "8081"
        volumes:
              - ./data/flink-master:/data
        env_file:
              - ./config/hadoop/hadoop.env
        depends_on:
              - namenode
              - datanode
    flink-worker:
        image: bde2020/flink-worker:1.2.0-hadoop2.7
        hostname: flink-worker
        container_name: flink-worker
        environment:
              FLINK_MASTER_PORT_6123_TCP_ADDR: "flink-master"
              CSS_SOURCE: "flink-dashboard"
              VIRTUAL_HOST: flink-worker.big-data-europe.local
              VIRTUAL_PORT: "8080"
        depends_on:
              - flink-master
    producer:
        image: producer
        build:
            context: .
            dockerfile: sc4-producer.dockerfile
        container_name: producer
        environment:
              HDFS_URL: hdfs://namenode:8020
              INIT_DAEMON_STEP: floating_producer
              FLINK_MASTER_PORT_6123_TCP_ADDR: "flink-master"
              FLINK_MASTER_PORT_6123_TCP_PORT: "6123"
        env_file:
              - ./config/hadoop/hadoop.env
    consumer:
        image: consumer
        build:
            context: .
            dockerfile: sc4-consumer.dockerfile
        container_name: consumer
        environment:
              HDFS_URL: hdfs://namenode:8020
              INIT_DAEMON_STEP: floating_consumer
              FLINK_MASTER_PORT_6123_TCP_ADDR: "flink-master"
              FLINK_MASTER_PORT_6123_TCP_PORT: "6123"
        env_file:
              - ./config/hadoop/hadoop.env
    monitor:
        image: bde2020/pipeline-monitor-frontend:0.1.0
        hostname: monitor
        container_name: monitor
        links:
            - identifier:backend
        depends_on:
            - identifier
        environment:
              VIRTUAL_HOST: monitor.big-data-europe.local

    identifier:
        image: semtech/mu-identifier:1.0.0
        hostname: identifier
        container_name: identifier

    dispatcher:
        image: semtech/mu-dispatcher:1.0.1
        hostname: dispatcher
        container_name: dispatcher
        volumes:
            - ./config:/config
# into the image copy

    database:
        build:
            context: .
            dockerfile: sc4-database.dockerfile
        image: bde2020/sc4-database
        hostname: database
        container_name: database
        environment:
            - SPARQL_UPDATE=true
            - DEFAULT_GRAPH=http://mu.semte.ch/application
            - VIRTUAL_HOST=virtuoso.big-data-europe.local
            - VIRTUAL_PORT=8890
# see Dockerfile: COPY ../data/db /data

    pipeline:
        image: bde2020/mu-pipeline-service:0.1.0
        hostname: pipeline
        container_name: pipeline

    initdaemon:
        image: bde2020/mu-init-daemon-service:0.1.0
        hostname: initdaemon
        container_name: initdaemon

    integratorui:
        image: bde2020/integrator-ui:latest
        hostname: integratorui
        container_name: integratorui
        volumes:
            - ./config/integrator:/app/config
        environment:
            VIRTUAL_HOST: demo.big-data-europe.local
# into the image copy

    csswrapper:
        image: bde2020/nginx-proxy-with-css
        hostname: csswrapper
        container_name: csswrapper
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
# into the image define docker host
